### ISSUE TITLE
AttributeError: 'str' object has no attribute 'isnumeric'

### ISSUE THREAD

**Issue by pphanwang** [vgrabovets/multi_rake#30]
i us  python 2.7   this is  code   
import pytest
from multi_rake import Rake
rake = Rake(
        min_chars=3,
        max_words=3,
        min_freq=1,
        lang_detect_threshold=50,
        max_words_unknown_lang=2,
        generated_stopwords_percentile=80,
        generated_stopwords_max_len=3,
        generated_stopwords_min_freq=2,
    )

text_en = (
        'Compatibility of systems of linear constraints over the set of '
        'natural numbers. Criteria of compatibility of a system of linear '
        'Diophantine equations, strict inequations, and nonstrict inequations '
        'are considered. Upper bounds for components of a minimal set of '
        'solutions and algorithms of construction of minimal generating sets '
        'of solutions for all types of systems are given. These criteria and '
        'the corresponding algorithms for constructing a minimal supporting '
        'set of solutions can be used in solving all the considered types of '
        'systems and systems of mixed types.'
    )

result = rake.apply(text_en)
============================================================

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-7-da5eb77e5e16> in <module>()
----> 1 result = rake.apply(text_en)

/usr/local/lib/python2.7/dist-packages/multi_rake-0.0.1-py2.7.egg/multi_rake/algorithm.pyc in apply(self, text, text_for_stopwords)
     85         )
     86 
---> 87         word_scores = Rake._calculate_word_scores(phrase_list)
     88 
     89         keywords = self._generate_candidate_keyword_scores(

/usr/local/lib/python2.7/dist-packages/multi_rake-0.0.1-py2.7.egg/multi_rake/algorithm.pyc in _calculate_word_scores(phrase_list)
    184 
    185         for phrase in phrase_list:
--> 186             word_list = separate_words(phrase)
    187             word_list_length = len(word_list)
    188             word_list_degree = word_list_length - 1

/usr/local/lib/python2.7/dist-packages/multi_rake-0.0.1-py2.7.egg/multi_rake/utils.pyc in separate_words(text)
     29 
     30     for word in text.split():
---> 31         if not word.isnumeric():
     32             words.append(word)
     33 

AttributeError: 'str' object has no attribute 'isnumeric'

**Comment by vgrabovets** [comment]
It doesn't work with python 2.7. You need python 3.6 or later.
